Added support for `eth_` on `akula-rpc`
akula-bft/akula pull request #165
Opened 2022-03-10 10:38 UTC by Giulio2002

2022-03-16 17:01 UTC, vorot93 requested changes

2022-03-16 17:01 UTC, vorot93 commented on src/rpc/mod.rs
> +                            .unwrap();
Please check unwrap usage. Invalid RPC parameters should be handled properly, not bump into unwraps.

2022-03-16 17:01 UTC, vorot93 commented on src/rpc/mod.rs
> +        let block_number = match block_number {
`if let`

2022-03-16 17:01 UTC, vorot93 commented on src/rpc/mod.rs
> +        match block_number {
`if let`

2022-03-17 10:51 UTC, Giulio2002 commented on src/rpc/eth.rs
> +            50_000_000
what about making gaslimit equivalent to header's gas limit?

2022-03-21 01:23 UTC, vorot93 approved these changes

2022-03-21 01:23 UTC, merged